### ISSUE TITLE
Compatibility with SpecFlow 3.7.13, MsTest and MSDI 5.0.1

### ISSUE THREAD

**Issue by shaundodimead** [solidtoken/SpecFlow.DependencyInjection#37] opened 2021-03-02 21:27 UTC
I've tried the nuget package in my netcoreapp3.1 project with SpecFlow 3.7.13 and SpecFlow.MsTest and I kept getting 

```
System.MissingMethodException
  HResult=0x80131513
  Message=Method not found: 'Void BoDi.ObjectContainer.RegisterTypeAs(System.String)'.
  Source=SolidToken.SpecFlow.DependencyInjection.SpecFlowPlugin
  StackTrace:
   at SolidToken.SpecFlow.DependencyInjection.DependencyInjectionPlugin.<Initialize>b__1_0(Object sender, CustomizeGlobalDependenciesEventArgs args) in D:\a\1\s\SpecFlow.DependencyInjection\DependencyInjectionPlugin.cs:line 33
   at TechTalk.SpecFlow.Plugins.RuntimePluginEvents.RaiseCustomizeGlobalDependencies(ObjectContainer container, SpecFlowConfiguration specFlowConfiguration)
   at TechTalk.SpecFlow.Infrastructure.ContainerBuilder.CreateGlobalContainer(Assembly testAssembly, IRuntimeConfigurationProvider configurationProvider)
   at TechTalk.SpecFlow.MSTest.SpecFlowPlugin.MsTestContainerBuilder.CreateGlobalContainer(Assembly testAssembly, IRuntimeConfigurationProvider configurationProvider)
   at TechTalk.SpecFlow.TestRunnerManager.CreateTestRunnerManager(Assembly testAssembly, IContainerBuilder containerBuilder)
   at TechTalk.SpecFlow.TestRunnerManager.GetTestRunnerManager(Assembly testAssembly, IContainerBuilder containerBuilder, Boolean createIfMissing)
   at TechTalk.SpecFlow.TestRunnerManager.OnTestRunStart(Assembly testAssembly, IContainerBuilder containerBuilder)
   at io_myproject_test_MSTestAssemblyHooks.AssemblyInitialize(TestContext testContext) in D:\source\myproject\myproject\myproject\src\test\obj\Debug\netcoreapp3.1\MSTest.AssemblyHooks.cs:line 22
```

Spewing out when running the tests. I cloned the repo, upgraded the packages to MSDI 5.01, Specflow, 3.7.13, and in the test project SpecFlow mstest 3.7.13, (i converted the step defs), swtiched xunit to mstest.testadapter and updated microsoft.net.test.sdk fpr 16.9.1, and all the tests pass, and it works in my project.

I'm not sure what to do with that information, other than suggest maybe something has changed between MSDI 3.1.6->5.0.1 and SpecFlow 3.3.0->3.7.13, and a new build might be needed to satisfy whatever it doesn't like above. The MsTest switch in the test projects was really just to make sure I could test and compare against what was breaking my stuff.

**Comment by mbhoek** [comment] 2021-03-06 09:18
Thank you for your report 👍. An update to the package is overdue, I will make an effort to release it soon.

**Comment by mbhoek** [comment] 2021-03-08 13:50
I've confirmed that the [current release](https://github.com/solidtoken/SpecFlow.DependencyInjection/releases/tag/v0.6.0) is not compatible with SpecFlow 3.7.13 or up. 
Previous releases up to and including SpecFlow 3.6.23 do work. 

For the future, I would like a mechanism that automatically tests the latest SpecFlow version against the current released plugin, like a [dependabot](https://github.blog/2020-06-01-keep-all-your-packages-up-to-date-with-dependabot/) for SpecFlow. In the mean time, an updated version of the plugin will be released later this week.

**Comment by mbhoek** [comment] 2021-03-10 22:08
AFAICT it is a breaking change in the new version of the BoDi library SpecFlow has introduced in v3.7. 
This might not be an issue for SpecFlow because their policy is to only [support the latest Major.Minor version](https://specflow.org/support/).

The plugin however assumed [SemVer](https://semver.org/#spec-item-8), i.e. that a breaking change would lead to a change in Major version. Assumptions..
Going forward the plugin will follow [SpecFlow versioning](https://specflow.org/blog/we-are-simplifying-our-specflow-and-net-version-support/), so a Major.Minor release of the plugin for a new Major.Minor release of SpecFlow. Specific enhancements to the plugin will be released as patch versions.

**Closed as completed** 2021-03-10 22:40 UTC
Labels: bug

**Comment by shaundodimead** [comment] 2021-03-10 22:52
Awesome - works for me!
